server:
  port: 10086

spring: #表示该配置直接为Spring容器负责处理
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #表示该配置直接为Spring容器负责处理
    driver-class-name: com.mysql.cj.jdbc.Driver  #配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.3.68:3307/shiro?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123
    filters: stat,wall,slf4j  #druid监控配置  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间
  # redis 配置
  redis:
    host: 192.168.3.68
    port: 6379
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: cn.mainfunc.test.model
  mapper-locations: classpath:/mapper/*.xml
#logback输出日志配置
#日志配置
logging:
  config: classpath:config/logback-spring.xml
  level:
   cn.mainfunc.test.mapper.UserMapper: debug
